type: segment-batch
id: null
relationships:
  parentFolder:
    data:
      id: ${rootfolder_id}
      type: folder-segment
attributes:
  - audienceId: ${audience_id}
    countPopulation: true
    name: Preferred Season - Summer
    rule:
        type: And
        conditions:
          - conditions:
              - type: Value
                leftValue:
                  name: preferred_season
                  visibility: clear
                operator:
                  not: false
                  rightValue: Summer
                  type: Equal
                exclude: false
            type: And
            description: 'Preferred Season - Summer'
            segmentInsightDashboardId: null
