name: td push
description: push a test TD workflow into Treasure Data
inputs:
  proj_dirs:
    description: List of project directories to push to TD. String with "|" delimiter, ie abc|def|xyz
    required: true
  fbranch:
    description: name of current branch. Used to label project files and data in TD
    required: true
  prev_build_sha:
    description: sha of the previous build/commit for the current branch. Used to make a "git diff" call and get changed files
    required: true
  curr_build_sha:
    description: sha of the current build/commit for the current branch. Used to make a git diff call and get changed files
    required: true
  dply_version:
    description: version of the main release to be deployed. 
    required: true
  api_token:
    description: pipe-delimited list of API tokens to used with each deployment event
    required: true
  wf_endpoint:
    description: TD WF URL to make API calls to with the deployment event
    required: true
  env_label:
    description: environment label (dev, qa, et) to label each project with
    required: true
runs:
  using: "composite" #This is the option to use if we're going to run .sh scripts inside this action
  steps:
    - name: run_push_script
      shell: bash
      env:
        INPUT_PROJ_DIRS: ${{ inputs.proj_dirs }}
        INPUT_PROJ_NAME: ${{ inputs.project_name }}
        INPUT_FBRANCH: ${{ inputs.fbranch }}
        INPUT_PREV_SHA: ${{ inputs.prev_build_sha }}
        INPUT_CURR_SHA: ${{ inputs.curr_build_sha }}
        INPUT_DPLY_VERSION: ${{ inputs.dply_version }}
        INPUT_API_TOKEN: ${{ inputs.api_token }}
        INPUT_WF_ENDPOINT: ${{ inputs.wf_endpoint }}
        INPUT_ENV_LABEL: ${{ inputs.env_label }}
      #the github.action_path is always available, and is how you access scripts in the same directory in composite actions
      run: ${{ github.action_path }}/script.sh
