drop table if exists app_analytics_tmp;

create table app_analytics_tmp (
  app_name BIGINT,
  analytics_id BIGINT,
  user_id VARCHAR,
  email VARCHAR,
  phone_number VARCHAR,
  device_id VARCHAR,
  event_time VARCHAR,
  event_id BIGINT,
  session_id BIGINT,
  event_type VARCHAR,
  version_name VARCHAR,
  adid VARCHAR,
  groups VARCHAR,
  idfa VARCHAR,
  platform VARCHAR,
  os_name VARCHAR,
  os_version VARCHAR,
  device_brand VARCHAR,
  device_manufacturer VARCHAR,
  device_model VARCHAR,
  device_carrier VARCHAR,
  device_type VARCHAR,
  device_family VARCHAR,
  location_lat DOUBLE,
  location_lng DOUBLE,
  country VARCHAR,
  language VARCHAR,
  city VARCHAR,
  region VARCHAR,
  dma VARCHAR,
  ip_address VARCHAR,
  event_properties VARCHAR,
  user_properties VARCHAR,
  uuid VARCHAR,
  time BIGINT
);