drop table if exists ${stg}_${sub}.${tbl};

create table ${stg}_${sub}.${tbl} (invalid_email varchar);

INSERT INTO ${stg}_${sub}.${tbl}
    (invalid_email)
VALUES
    ('NOEMAIL@GMAIL.COM'),
    ('NO@DGDG.COM'),
    ('NA@GMAIL.COM'),
    ('NONE@NONE.COM'),
    ('NO@NO.COM'),
    ('NO@EMAIL.COM'),
    ('NONE@GMAIL.COM'),
    ('NOEMAIL@NOEMAIL.COM'),
    ('NOMAIL@MAIL.COM'),
    ('NOEMAIL@YAHOO.COM'),
    ('NO@GMAIL.COM'),
    ('NONE@EMAIL.COM'),
    ('NA@NA.COM'),
    ('NONE@YAHOO.COM'),
    ('NONE@AOL.COM'),
    ('NA@YAHOO.COM'),
    ('NOEAMIL@DGDG.COM'),
    ('NOMAIL@GMAIL.COM'),
    ('NOEMAIL@EMAIL.COM'),
    ('NOEMAIL@MAIL.COM'),
    ('NO@NONE.COM'),
    ('NONE@NO.COM'),
    ('NOE-MAIL@YAHOO.COM'),
    ('NANA@YAHOO.COM'),
    ('NOEMAIL@NOEMAOL.COM'),
    ('NOEMAIL@HOME.COM'),
    ('NOMAIL@YAHOO.COM'),
    ('NA@D.COM'),
    ('NON@NO.COM'),
    ('NONEATTHISTIME@NA.COM'),
    ('NOEMAIL@NO.COM'),
    ('NOEMAI@GMAIL.COM'),
    ('NON@NONE.COM'),
    ('NON@NON.COM'),
    ('NO@YAHOO.COM'),
    ('NO@AOL.COM'),
    ('NO@NOEMAIL.COM'),
    ('WNG@A.COM'),
    ('DNH@A.COM'),
    ('NEEDEMAIL@YAHOO.COM'),
    ('UNKNOWN@AOL.COM'),
    ('ABC@GMAIL.COM'),
    ('NAN@EMAIL.COM'),
    ('DONOTHAVE@EMAIL.COM'),
    ('DNH@AOL.COM'),
    ('CD@CD.COM'),
    ('DNH@EMAIL.COM'),
    ('EMAIL@EMAIL.COM'),
    ('DNA@GMAIL.COM'),
    ('YES@YAHOO.COM'),
    ('UNKOWN@GMAIL.COM')
-- add additional emails below
;